### PR TITLE
Improvements and tests

### PR DESCRIPTION
**Pull request by sweptsquash**
This pull request builds upon the prior PR by extending functionality, improving code quality, and enhancing the project's workflows and documentation. Key updates include the introduction of new GitHub workflows, extensive codebase refactoring, improved examples, and updated dependencies.

### Workflow Enhancements:
- New run-tests.yml Workflow: Introduced a GitHub Actions workflow for running tests across multiple environments to ensure cross-environment compatibility and reliability. [[Details]](https://github.com/jamesread/lan-party-publisher-php/compare/master...sweptsquash:lan-party-publisher-php-improvements:feat/ImprovementsAndTests?expand=1)

### Codebase Refactoring:

- `Event` Class Enhancements (`lib/Event.php`):
  - Adopted typed properties for improved type safety and clarity.
  - Added a constructor for streamlined property initialization.
  - Introduced a `make` method for creating instances with additional options.
- `ModelBase` Class Updates (`lib/ModelBase.php`):
  - Simplified the constructor for easier maintenance.
  - Leveraged typed properties for better readability and stricter type enforcement.
- New `SleepingEnum` Class (`lib/Enums/SleepingEnum.php`):
  - Added a dedicated enum for representing sleeping arrangements, enhancing type safety and improving overall code expressiveness.

### Documentation and Examples:
- `README.md` Updates:
  - Refined the package description and usage instructions for clarity and accessibility.
- Example Script Modernization:
  - Updated and streamlined example scripts to align with the refactored codebase:
    - `basic.php`: Modernized to reflect recent API changes. [[Details]](https://github.com/jamesread/lan-party-publisher-php/compare/master...sweptsquash:lan-party-publisher-php-improvements:feat/ImprovementsAndTests?expand=1)
    - `multipleVenuesWithEvents.php`: Simplified and improved readability. [[Details]](https://github.com/jamesread/lan-party-publisher-php/compare/master...sweptsquash:lan-party-publisher-php-improvements:feat/ImprovementsAndTests?expand=1)
    - `singleVenueWithMultipleEvents.php`: Updated to better illustrate usage scenarios. [[Details]](https://github.com/jamesread/lan-party-publisher-php/compare/master...sweptsquash:lan-party-publisher-php-improvements:feat/ImprovementsAndTests?expand=1)

### Dependency Management:
- `composer.json` Enhancements:
  - Added new development dependencies for testing and analysis.
  - Updated PHP version requirement to reflect the latest compatibility standards.
  - Introduced additional scripts for static analysis, linting, and test execution.

This PR represents a comprehensive step forward in maintaining code quality, modernizing workflows, and enhancing the project's usability for developers and end-users alike.

Please review in the following order:

1. https://github.com/jamesread/lan-party-publisher-php/pull/4
2. https://github.com/jamesread/lan-party-publisher-php/pull/3
3. https://github.com/jamesread/lan-party-publisher-php/pull/5

### CODE REVIEW

**Comment by sweptsquash** [comment]
@jamesread ready for review.

**Comment by sweptsquash** [comment]
@jamesread any update on this one?

**Comment by jamesread** [comment]
Heya, I haven't forgotten - I'm just super busy with work stuff and some other projects at the moment. I'll revert back as soon as I can.

**Comment by sweptsquash** [comment]
> Heya, I haven't forgotten - I'm just super busy with work stuff and some other projects at the moment. I'll revert back as soon as I can.

No problems :)

**Comment by jamesread** [comment]
Heya @sweptsquash , I just wanted to say thanks so much for your patience, and your willingness to split this up nicely. I like what you've done with the extra tests, so overall, great job.

Happily merged :-)

**Comment by sweptsquash** [comment]
> Heya @sweptsquash , I just wanted to say thanks so much for your patience, and your willingness to split this up nicely. I like what you've done with the extra tests, so overall, great job.
> 
> Happily merged :-)

Thank you 😊 glad you like the changes. Any chance of a new tag being published?

**Pull request merged**
