### PR TITLE
Add Gitignore

### PR DESCRIPTION
**Pull request by sweptsquash**
This PR introduces a standard `.gitignore` file to streamline repository management and prevent unnecessary files from being committed. The added `.gitignore` ensures that common files and directories such as `vendor`, editor configurations, build artifacts, and documentation are excluded. This helps maintain a cleaner repository by avoiding potential bloat and irrelevant content.

### Summary of .gitignore Contents:
- Composer Related:
  - `composer.lock`
  - `/vendor`
- Caches:
  - `.phpunit.cache`
  - `.phpunit.result.cache`
  - `/build`
- Editor Configurations:
  - `/.idea`
  - `/.fleet`
  - `/.vscode`
- Miscellaneous:
  - `phpunit.xml`
  - `/docs`
  - `/coverage`

These exclusions ensure the repository remains focused on the necessary code and configuration while preventing accidental commits of temporary or environment-specific files.

Please review in the following order:

1. https://github.com/jamesread/lan-party-publisher-php/pull/4
2. https://github.com/jamesread/lan-party-publisher-php/pull/3
3. https://github.com/jamesread/lan-party-publisher-php/pull/5

### CODE REVIEW

**Comment by sweptsquash** [comment]
@jamesread ready for review.

**Comment by jamesread** [comment]
Heya, thanks for breaking this up into smaller PRs, that makes things much easier to comment on. I know that's a lot of work, so, thank you for understanding 😊 

1. The composer.lock files should always be committed, like NPM package lock files, as they prevent dependency drift by hashing dependencies. See this described in the composer docs here: https://getcomposer.org/doc/01-basic-usage.md#commit-your-composer-lock-file-to-version-control

2. vendor/ is for vendored deps, meaning deps that you want to include in your source tree, and not download from packagist or npm or whatever, so vendor should not be ignored, we would want to commit files in this directory (if if it's empty now). 

3. There are no docs dir or phpunit.xml file (yet), but why would we want to ignore either of those? 

I'd really like to work with you to get your good ideas into the project, I really value contributors and contributions to my projects - so I hope you're not discouraged from my first few code reviews? We'll learn each other's style and get more efficient as we go long, I'm sure? Thanks again for the time you're putting into this.

**Comment by sweptsquash** [comment]
> Heya, thanks for breaking this up into smaller PRs, that makes things much easier to comment on. I know that's a lot of work, so, thank you for understanding 😊
> 
> 1. The composer.lock files should always be committed, like NPM package lock files, as they prevent dependency drift by hashing dependencies. See this described in the composer docs here: https://getcomposer.org/doc/01-basic-usage.md#commit-your-composer-lock-file-to-version-control
> 2. vendor/ is for vendored deps, meaning deps that you want to include in your source tree, and not download from packagist or npm or whatever, so vendor should not be ignored, we would want to commit files in this directory (if if it's empty now).
> 3. There are no docs dir or phpunit.xml file (yet), but why would we want to ignore either of those?
> 
> I'd really like to work with you to get your good ideas into the project, I really value contributors and contributions to my projects - so I hope you're not discouraged from my first few code reviews? We'll learn each other's style and get more efficient as we go long, I'm sure? Thanks again for the time you're putting into this.

1. Majority of packages I've worked with do not commit the `composer.lock` but if you'd prefer the `composer.lock` committed that's ok.

2. Similar above the `vendor` folder is often ignored to reduce the repo's size, but also because when performing `composer require jamesread/lan-party-publisher-php` any required dependencies will be installed into the projects root vendor folder, therefore its good practice to not commit the `vendor` folder. But in this case I've removed it from the gitignore and committed it to respect the requirements.

3. These have been removed.

**Comment by jamesread** [comment]
Heya, 

1. Yeah, but other projects not committing the lock file is certainly wrong, as per the docs - it protects against drifting deps. Pretty much all package managers work like this nowadays. 
 
2. Oops! I was totally wrong about the vendor dir! I'm so sorry, my brain is more used to golang nowadays, and dependencies are stored in a common directory shared across projects, and the vendor dir is where deps are stored that you want to version. I'm sorry, I'm just used to seeing golang more and you're totally right - because in php composer stores everything in this vendor dir. 

If you revert 2 and ignore vendor again like you did originally I'll accept this PR and we'll move onto the next one! :-) I'm certain the other PRs will go quicker!

**Comment by sweptsquash** [comment]
> Heya,
> 
> 1. Yeah, but other projects not committing the lock file is certainly wrong, as per the docs - it protects against drifting deps. Pretty much all package managers work like this nowadays.
> 2. Oops! I was totally wrong about the vendor dir! I'm so sorry, my brain is more used to golang nowadays, and dependencies are stored in a common directory shared across projects, and the vendor dir is where deps are stored that you want to version. I'm sorry, I'm just used to seeing golang more and you're totally right - because in php composer stores everything in this vendor dir.
> 
> If you revert 2 and ignore vendor again like you did originally I'll accept this PR and we'll move onto the next one! :-) I'm certain the other PRs will go quicker!

@jamesread Pushed the commits to remove the vendor folder and restored it to the gitignore

**Comment by jamesread** [comment]
Merged! Thanks very much. :-) Appreciate your patience.

**Pull request merged**
